@startuml
'https://plantuml.com/sequence-diagram

class HeroAircraft {
    - strategychange:int
    - shootNum:int
    - power:int
    - direction:int
    -{static} HeroAircraft:Hero
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    - strategy:Strategy

    + {static}getHero():HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
    + getstrategychange():int
    + setStrategy(Strategy strategy):void
    + changeStrategy(Strategy strategy):void
    + getStrategy():Strategy
}

@enduml